name: Check Expired Videos

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 0:00 运行
  workflow_dispatch:      # 允许手动触发

jobs:
  check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests notion-client beautifulsoup4
    
    - name: Create Cookies directory
      run: mkdir -p Cookies
    
    - name: Create cookie file
      run: |
        echo "${{ secrets.BILIBILI_COOKIES }}" > Cookies/2.txt
    
    - name: Run check script
      env:
        NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
        DATABASE_ID: ${{ secrets.DATABASE_ID }}
      run: python Check_Expired.py
