name: Build TodoList

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        architecture: 'x64'

    - name: Create icon
      run: |
        python -c "from PIL import Image; img = Image.new('RGB', (64, 64), 'green'); img.save('app.ico')"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pystray pillow pyinstaller

    - name: Build executable
      run: |
        pyinstaller --name TodoList --onefile --noconsole --hidden-import PIL --hidden-import pystray._win32 --hidden-import PIL._tkinter_finder --icon=app.ico main.py

    - name: Create empty todos.json
      run: |
        echo "[]" > dist/todos.json

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: TodoList
        path: |
          dist/TodoList.exe
          dist/todos.json
