name: Build 步骤之前运行，导致 `PIL` 模块还没有安装。

你可以通过将 `Install dependencies` TodoList

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - 步骤移到 `Create icon` 步骤之前来解决这个问题。修改后的工作流文件如下：

```yaml name: Checkout code
      uses: actions/checkout@
name: Build TodoList

on:
  workflow_dispatch:

v4

    - name: Set up Python
      uses: actions/setupjobs:
  build:
    runs-on: windows-latest

    steps-python@v4
      with:
        python-version::
    - name: Checkout code
      uses: actions/ '3.11'
        architecture: 'x64'

    - name: Install dependenciescheckout@v4

    - name: Set up Python
      uses:  # 安装依赖库的步骤提前
      run: |
        python - actions/setup-python@v4
      with:
        python-versionm pip install --upgrade pip
        pip install pystr: '3.11'
        architecture: 'x64'

    - nameay pillow pyinstaller

    - name: Create icon
     : Install dependencies
      run: |
        python - run: |
        python -c "from PIL import Image;m pip install --upgrade pip
        pip install pystray pillow pyinstaller

    - name: Create icon
      img = Image.new('RGB', (64, 64), 'green'); img.save(' run: |
        python -c "from PIL import Image;app.ico')"

    - name: Build executable
      run: |
        pyinstaller --name TodoList --onefile --n img = Image.new('RGB', (64, 64), 'green'); img.save('app.ico')"

oconsole --hidden-import PIL --hidden-import pystray._win32    - name: Build executable
      run: --hidden-import PIL._tkinter_finder --icon= |
        pyinstaller --name TodoList --onefile --napp.ico main.py

    - name: Create empty todos.json
oconsole --hidden-import PIL --hidden-import pystray      run: |
        echo "[]" > dist/todos.json

    -._win32 --hidden-import PIL._tkinter_finder --icon= name: Upload artifacts
      uses: actions/upload-artapp.ico main.py

    - name: Create empty todos.json
ifact@v4
      with:
        name: TodoList
        path      run: |
        echo "[]" > dist/todos.json

   : |
          dist/TodoList.exe
          dist/t - name: Upload artifacts
      uses: actions/upload-artodos.json
